### ISSUE TITLE
🚀 Feature: Set up transitions between screens (with movement of rocket)

### ISSUE THREAD

**Issue by arjunr00** [uclaacm/Playnet#10]
Using the [anime.js](https://animejs.com/) library will make this really easy.

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by reginawang99** [comment]
We can also use lottie and have dynamic text! https://github.com/airbnb/lottie-web/issues/238

**Comment by BryanPan342** [comment]
hmm not sure if this is viable tho.. i dug a little deeper and I cant find a way to incorporate it without creating our own AE file..

RN the way they are demonstrating usage is by adding a text_demo.js file which is a `json` that holds the animation data (i.e. the AE file). From there, they are looking at the minified `json` and then resetting the text values to values they want. It's certainly doable, but I would advise creating our own if we were to use lottie?

Depending on how we want the words to be animated in we can use a variety of libraries tho!

**Comment by reginawang99** [comment]
oooo yeee ill be doing aftereffects for the data center stuff and it seems pretty easy! Especially for the rocket stuff which will be just translation, it just requires a few clicks to make a an animation @BryanPan342 what do you think?

**Comment by BryanPan342** [comment]
i wonder how the animation will look like.. do we need to make it responsive? I'm wondering if lottie will restrict us because its basically just a div element with a specified size.. actually now that I'm writing this out I think it will be fine haha

**Comment by reginawang99** [comment]
yeee if we want to make it responsive maybe lottie wouldnt be best, tho im not sure we going to make the intro responsive? besides the buttons

**Comment by reginawang99** [comment]
oh shoot sorry, i didnt notice that you took it @BryanPan342 we don't have to do lottie haha do whatevs you comfy with :) mbmb pls ignore

**Comment by BryanPan342** [comment]
@reginawang99 does this ticket still hold?

**Comment by reginawang99** [comment]
yee but i can also do it in AE/look into animejs! anything is good~
