### ISSUE TITLE
🚀 Feature: A3 game wrapper

### ISSUE THREAD

**Issue by BryanPan342** [uclaacm/Playnet#110]
* Wrapper function for the A3 game
* next functionality
* return to the variables
* return to start
* game context!!

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
#121 closes this

**Comment by reginawang99** [comment]
:( oop gonna make a new ticket for the other pr! since it doesnt really close this
