### ISSUE TITLE
🚀 Feature: A3 debug (29)

### ISSUE THREAD

**Issue by BryanPan342** [uclaacm/Playnet#113]
- [ ] debug - slide 29

https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=1918%3A79119

blocks completion of #115 

---

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by reginawang99** [comment]
must use 🧠  to think of:
- list of error names
- determine `# errors` + `errors popping up` + `overall quality of recommendation` 
     - based off of # days spent developing & debugging

<for design/ideas help can ask @reginawang99 cuz dont want too much work on designer, tho tbh whoever does this can figure it out 🥇 >
