### ISSUE TITLE
🚀 Feature: [Game 1] Set up generation of choices and corresponding ciphers

### ISSUE THREAD

**Issue by arjunr00** [uclaacm/Playnet#12]
This would be a utility script which contains functions that can generate some kind of representation of a set of choices to choose from and a particular (Ceasarean?) cipher which corresponds to one of them.

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
this is actually a really cool issue :) I think it would be cool to learn for any newcomers @uclaacm/playnet-team but if not I don't mind taking this ticket!

**Comment by reginawang99** [comment]
oki! maybe one of our newer devs might be interested :) ill help them get setup sometime later in the week!

**Comment by reginawang99** [comment]
forgot to update but they want to do other things haha 
- [ ]  👋 I may be able to implement this feature request

**Comment by BryanPan342** [comment]
@reginawang99 are u takin this one? If not I can take it

**Comment by reginawang99** [comment]
nope, go ahead :)
