### ISSUE TITLE
🚀 Feature: add netlify integration? or some sort of deploy preview functionality

### ISSUE THREAD

**Issue by BryanPan342** [uclaacm/Playnet#5]
let's add a netlify integration! or we can deploy to github pages if that is more ACM's jam

Either ACM can do it, or CL can do it :) 

thoughts @reginawang99 @arjunr00 

### Use Case

makes reviewing changes easier :) and CI/CD is cool

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by malsf21** [comment]
Oops didn't catch this issue! I integrated Netlify + enabled deploy previews, I think this ticket is good to close - @BryanPan342 is this what you were thinking of?

**Comment by BryanPan342** [comment]
yup! i think i just added this to make sure I didn't forget haha
