### ISSUE TITLE
🚀 Feature: last two slides of activity 2

### ISSUE THREAD

**Issue by reginawang99** [uclaacm/Playnet#62]
- better display of compressed vs uncompressed results => [see this link](https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=1749%3A75396)
- More information area => [see this figma slide](https://www.figma.com/file/7DzNiScbp6t3x0p86pz5P9/Playnets?node-id=1748%3A75177)

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by mattxwang** [comment]
Not sure exactly how relevant this is, but this repo has always been a fave of mine: https://github.com/alex/what-happens-when
