### ISSUE TITLE
👀 Tracking: make activity 1 game 1 easier

### ISSUE THREAD

**Issue by reginawang99** [uclaacm/Playnet#66]
### Overview:
Activity 1 Game 1 is quite difficult, and might frustrate the kids.

### Checklist
- [x] Playing word aloud #72 
- [x] Help out kids if they mess up too much #71 

### Ideas that need testing (feel free to contribute ideas)
- Words don’t stick in head fix
        - different length words
        - scramble everything but the first letter
        - ??
- Making first part of game = learn 3 words (rather than 4)

--- 
This is a 👀 Tracking Issue

**Comment by BryanPan342** [comment]
@reginawang99 is this a tracking issue?

**Comment by reginawang99** [comment]
@BryanPan342  oops yea it is, i should change it

**Comment by reginawang99** [comment]
should be good for now! may reopen if its still an issue
